# Generated by Django 5.2.9 on 2026-01-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(default='lorem'),
        ),
    ]
